package ru.fiarr4ik.contractorapi;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;
import ru.fiarr4ik.contractorapi.services.CountryService;

@Service
public class CountryDataLoader implements CommandLineRunner {


    @Autowired
    private CountryService countryService;

    @Override
    public void run(String... args) throws Exception {
        countryService.addCountry("ABH", "Абхазия");
        countryService.addCountry("ABW", "Аруба");
        countryService.addCountry("AFG", "Афганистан");
        countryService.addCountry("AGO", "Ангола");
        countryService.addCountry("AIA", "Ангилья");
        countryService.addCountry("ALA", "Эландские Острова");
        countryService.addCountry("ALB", "Албания");
        countryService.addCountry("AND", "Андорра");
        countryService.addCountry("ANT", "Антильские острова (Нидерландские Антилы)");
        countryService.addCountry("ARE", "Объединенные Арабские Эмираты");
        countryService.addCountry("ARG", "Аргентина");
        countryService.addCountry("ARM", "Армения");
        countryService.addCountry("ASM", "Американское Самоа");
        countryService.addCountry("ATA", "Антарктида");
        countryService.addCountry("ATF", "Французские Южные Территории");
        countryService.addCountry("ATG", "Антигуа и Барбуда");
        countryService.addCountry("AUS", "Австралия");
        countryService.addCountry("AUT", "Австрия");
        countryService.addCountry("AZE", "Азербайджан");
        countryService.addCountry("BDI", "Бурунди");
        countryService.addCountry("BEL", "Бельгия");
        countryService.addCountry("BEN", "Бенин");
        countryService.addCountry("BES", "Бонэйр, Синт-Эстатиус и Саба");
        countryService.addCountry("BFA", "Буркина-Фасо");
        countryService.addCountry("BGD", "Бангладеш");
        countryService.addCountry("BGR", "Болгария");
        countryService.addCountry("BHR", "Бахрейн");
        countryService.addCountry("BHS", "Багамы");
        countryService.addCountry("BIH", "Босния и Герцеговина");
        countryService.addCountry("BLM", "Сен-Бартелеми");
        countryService.addCountry("BLR", "Беларусь");
        countryService.addCountry("BLZ", "Белиз");
        countryService.addCountry("BMU", "Бермуды");
        countryService.addCountry("BOL", "Боливия, Многонациональное Государство");
        countryService.addCountry("BRA", "Бразилия");
        countryService.addCountry("BRB", "Барбадос");
        countryService.addCountry("BRN", "Бруней-Даруссалам");
        countryService.addCountry("BTN", "Бутан");
        countryService.addCountry("BVT", "Остров Буве");
        countryService.addCountry("BWA", "Ботсвана");
        countryService.addCountry("CAF", "Центрально-Африканская Республика");
        countryService.addCountry("CAN", "Канада");
        countryService.addCountry("CCK", "Кокосовые (Килинг) Острова");
        countryService.addCountry("CHE", "Швейцария");
        countryService.addCountry("CHL", "Чили");
        countryService.addCountry("CHN", "Китай");
        countryService.addCountry("CIV", "Кот Д'Ивуар");
        countryService.addCountry("CMR", "Камерун");
        countryService.addCountry("COD", "Конго, Демократическая Республика");
        countryService.addCountry("COG", "Конго");
        countryService.addCountry("COK", "Острова Кука");
        countryService.addCountry("COL", "Колумбия");
        countryService.addCountry("COM", "Коморы");
        countryService.addCountry("CPV", "Кабо-Верде");
        countryService.addCountry("CRI", "Коста-Рика");
        countryService.addCountry("CUB", "Куба");
        countryService.addCountry("CUW", "Кюрасао");
        countryService.addCountry("CXR", "Остров Рождества");
        countryService.addCountry("CYM", "Острова Кайман");
        countryService.addCountry("CYP", "Кипр");
        countryService.addCountry("CZE", "Чешская Республика");
        countryService.addCountry("DEU", "Германия");
        countryService.addCountry("DJI", "Джибути");
        countryService.addCountry("DMA", "Доминика");
        countryService.addCountry("DNK", "Дания");
        countryService.addCountry("DOM", "Доминиканская Республика");
        countryService.addCountry("DZA", "Алжир");
        countryService.addCountry("ECU", "Эквадор");
        countryService.addCountry("EGY", "Египет");
        countryService.addCountry("ERI", "Эритрея");
        countryService.addCountry("ESH", "Западная Сахара");
        countryService.addCountry("ESP", "Испания");
        countryService.addCountry("EST", "Эстония");
        countryService.addCountry("ETH", "Эфиопия");
        countryService.addCountry("FIN", "Финляндия");
        countryService.addCountry("FJI", "Фиджи");
        countryService.addCountry("FLK", "Фолклендские Острова (Мальвинские)");
        countryService.addCountry("FRA", "Франция");
        countryService.addCountry("FRO", "Фарерские Острова");
        countryService.addCountry("FSM", "Микронезия, Федеративные Штаты");
        countryService.addCountry("GAB", "Габон");
        countryService.addCountry("GBR", "Соединенное Королевство");
        countryService.addCountry("GEO", "Грузия");
        countryService.addCountry("GGY", "Гернси");
        countryService.addCountry("GHA", "Гана");
        countryService.addCountry("GIB", "Гибралтар");
        countryService.addCountry("GIN", "Гвинея");
        countryService.addCountry("GLP", "Гваделупа");
        countryService.addCountry("GMB", "Гамбия");
        countryService.addCountry("GNB", "Гвинея-Бисау");
        countryService.addCountry("GNQ", "Экваториальная Гвинея");
        countryService.addCountry("GRC", "Греция");
        countryService.addCountry("GRD", "Гренада");
        countryService.addCountry("GRL", "Гренландия");
        countryService.addCountry("GTM", "Гватемала");
        countryService.addCountry("GUF", "Французская Гвиана");
        countryService.addCountry("GUM", "Гуам");
        countryService.addCountry("GUY", "Гайана");
        countryService.addCountry("HKG", "Гонконг");
        countryService.addCountry("HMD", "Остров Херд и Острова Макдональд");
        countryService.addCountry("HND", "Гондурас");
        countryService.addCountry("HRV", "Хорватия");
        countryService.addCountry("HTI", "Гаити");
        countryService.addCountry("HUN", "Венгрия");
        countryService.addCountry("IDN", "Индонезия");
        countryService.addCountry("IMN", "Остров Мэн");
        countryService.addCountry("IND", "Индия");
        countryService.addCountry("IOT", "Британская Территория в Индийском Океане");
        countryService.addCountry("IRL", "Ирландия");
        countryService.addCountry("IRN", "Иран, Исламская Республика");
        countryService.addCountry("IRQ", "Ирак");
        countryService.addCountry("ISL", "Исландия");
        countryService.addCountry("ISR", "Израиль");
        countryService.addCountry("ITA", "Италия");
        countryService.addCountry("JAM", "Ямайка");
        countryService.addCountry("JEY", "Джерси");
        countryService.addCountry("JOR", "Иордания");
        countryService.addCountry("JPN", "Япония");
        countryService.addCountry("KAZ", "Казахстан");
        countryService.addCountry("KEN", "Кения");
        countryService.addCountry("KGZ", "Киргизия");
        countryService.addCountry("KHM", "Камбоджа");
        countryService.addCountry("KIR", "Кирибати");
        countryService.addCountry("KNA", "Сент-Китс и Невис");
        countryService.addCountry("KOR", "Корея, Республика");
        countryService.addCountry("KWT", "Кувейт");
        countryService.addCountry("LAO", "Лаосская Народно-Демократическая Республика");
        countryService.addCountry("LBN", "Ливан");
        countryService.addCountry("LBR", "Либерия");
        countryService.addCountry("LBY", "Ливия");
        countryService.addCountry("LCA", "Сент-Люсия");
        countryService.addCountry("LIE", "Лихтенштейн");
        countryService.addCountry("LKA", "Шри-Ланка");
        countryService.addCountry("LSO", "Лесото");
        countryService.addCountry("LTU", "Литва");
        countryService.addCountry("LUX", "Люксембург");
        countryService.addCountry("LVA", "Латвия");
        countryService.addCountry("MAC", "Макао");
        countryService.addCountry("MAF", "Сен-Мартен");
        countryService.addCountry("MAR", "Марокко");
        countryService.addCountry("MCO", "Монако");
        countryService.addCountry("MDA", "Молдова, Республика");
        countryService.addCountry("MDG", "Мадагаскар");
        countryService.addCountry("MDV", "Мальдивы");
        countryService.addCountry("MEX", "Мексика");
        countryService.addCountry("MHL", "Маршалловы Острова");
        countryService.addCountry("MKD", "Республика Македония");
        countryService.addCountry("MLI", "Мали");
        countryService.addCountry("MLT", "Мальта");
        countryService.addCountry("MMR", "Мьянма");
        countryService.addCountry("MNE", "Черногория");
        countryService.addCountry("MNG", "Монголия");
        countryService.addCountry("MNP", "Северные Марианские Острова");
        countryService.addCountry("MOZ", "Мозамбик");
        countryService.addCountry("MRT", "Мавритания");
        countryService.addCountry("MSR", "Монтсеррат");
        countryService.addCountry("MTQ", "Мартиника");
        countryService.addCountry("MUS", "Маврикий");
        countryService.addCountry("MWI", "Малави");
        countryService.addCountry("MYS", "Малайзия");
        countryService.addCountry("MYT", "Майотта");
        countryService.addCountry("NAM", "Намибия");
        countryService.addCountry("NCL", "Новая Каледония");
        countryService.addCountry("NER", "Нигер");
        countryService.addCountry("NFK", "Остров Норфолк");
        countryService.addCountry("NGA", "Нигерия");
        countryService.addCountry("NIC", "Никарагуа");
        countryService.addCountry("NIU", "Ниуэ");
        countryService.addCountry("NLD", "Нидерланды");
        countryService.addCountry("NOR", "Норвегия");
        countryService.addCountry("NPL", "Непал");
        countryService.addCountry("NRU", "Науру");
        countryService.addCountry("NZL", "Новая Зеландия");
        countryService.addCountry("OMN", "Оман");
        countryService.addCountry("OST", "Южная Осетия");
        countryService.addCountry("PAK", "Пакистан");
        countryService.addCountry("PAN", "Панама");
        countryService.addCountry("PCN", "Питкэрн");
        countryService.addCountry("PER", "Перу");
        countryService.addCountry("PHL", "Филиппины");
        countryService.addCountry("PLW", "Палау");
        countryService.addCountry("PNG", "Папуа Новая Гвинея");
        countryService.addCountry("POL", "Польша");
        countryService.addCountry("PRI", "Пуэрто-Рико");
        countryService.addCountry("PRK", "Корея, Народно-Демократическая Республика");
        countryService.addCountry("PRT", "Португалия");
        countryService.addCountry("PRY", "Парагвай");
        countryService.addCountry("PSE", "Палестина, Государство");
        countryService.addCountry("PYF", "Французская Полинезия");
        countryService.addCountry("QAT", "Катар");
        countryService.addCountry("REU", "Реюньон");
        countryService.addCountry("ROU", "Румыния");
        countryService.addCountry("RUS", "Российская Федерация");
        countryService.addCountry("RWA", "Руанда");
        countryService.addCountry("SAU", "Саудовская Аравия");
        countryService.addCountry("SDN", "Судан");
        countryService.addCountry("SEN", "Сенегал");
        countryService.addCountry("SGP", "Сингапур");
        countryService.addCountry("SGS", "Южная Джорджия и Южные Сандвичевы Острова");
        countryService.addCountry("SHN", "Святая Елена, Остров Вознесения, Тристан-Да-Кунья");
        countryService.addCountry("SJM", "Шпицберген и Ян Майен");
        countryService.addCountry("SLB", "Соломоновы Острова");
        countryService.addCountry("SLE", "Сьерра-Леоне");
        countryService.addCountry("SLV", "Эль-Сальвадор");
        countryService.addCountry("SMR", "Сан-Марино");
        countryService.addCountry("SOM", "Сомали");
        countryService.addCountry("SPM", "Сент-Пьер и Микелон");
        countryService.addCountry("SRB", "Сербия");
        countryService.addCountry("SSD", "Южный Судан");
        countryService.addCountry("STP", "Сан-Томе и Принсипи");
        countryService.addCountry("SUR", "Суринам");
        countryService.addCountry("SVK", "Словакия");
        countryService.addCountry("SVN", "Словения");
        countryService.addCountry("SWE", "Швеция");
        countryService.addCountry("SWZ", "Свазиленд");
        countryService.addCountry("SXM", "Синт-Мартен (Нидерландская Часть)");
        countryService.addCountry("SYC", "Сейшелы");
        countryService.addCountry("SYR", "Сирийская Арабская Республика");
        countryService.addCountry("TCA", "Острова Теркс и Кайкос");
        countryService.addCountry("TCD", "Чад");
        countryService.addCountry("TGO", "Того");
        countryService.addCountry("THA", "Таиланд");
        countryService.addCountry("TJK", "Таджикистан");
        countryService.addCountry("TKL", "Токелау");
        countryService.addCountry("TKM", "Туркмения");
        countryService.addCountry("TLS", "Тимор-Лесте");
        countryService.addCountry("TON", "Тонга");
        countryService.addCountry("TTO", "Тринидад и Тобаго");
        countryService.addCountry("TUN", "Тунис");
        countryService.addCountry("TUR", "Турция");
        countryService.addCountry("TUV", "Тувалу");
        countryService.addCountry("TWN", "Тайвань (Китай)");
        countryService.addCountry("TZA", "Танзания, Объединенная Республика");
        countryService.addCountry("UGA", "Уганда");
        countryService.addCountry("UKR", "Украина");
        countryService.addCountry("UMI", "Малые Тихоокеанские Отдаленные Острова Соединенных Штатов / Внешние Малые Острова США");
        countryService.addCountry("URY", "Уругвай");
        countryService.addCountry("USA", "Соединенные Штаты");
        countryService.addCountry("UZB", "Узбекистан");
        countryService.addCountry("VAT", "Папский Престол (Государство - Город Ватикан)");
        countryService.addCountry("VCT", "Сент-Винсент и Гренадины");
        countryService.addCountry("VEN", "Венесуэла Боливарианская Республика");
        countryService.addCountry("VGB", "Виргинские Острова, Британские");
        countryService.addCountry("VIR", "Виргинские Острова, США");
        countryService.addCountry("VNM", "Вьетнам");
        countryService.addCountry("VUT", "Вануату");
        countryService.addCountry("WLF", "Уоллис и Футуна");
        countryService.addCountry("WSM", "Самоа");
        countryService.addCountry("WWW", "Международная компания");
        countryService.addCountry("YEM", "Йемен");
        countryService.addCountry("YUG", "Югославия");
        countryService.addCountry("ZAF", "Южная Африка");
        countryService.addCountry("ZMB", "Замбия");
        countryService.addCountry("ZWE", "Зимбабве");
    }
}